export type ArenaDeckSection = 'deck' | 'sideboard' | 'companion'

export type ArenaDeckCard = {
  quantity: number
  name: string
  section: ArenaDeckSection
  setCode?: string
  collectorNumber?: string
}

export type ParsedArenaDecklist = {
  cards: ArenaDeckCard[]
  mainDeckCount: number
  sideboardCount: number
  companionCount: number
}

const sectionHeaders: Record<string, ArenaDeckSection> = {
  deck: 'deck',
  sideboard: 'sideboard',
  companion: 'companion',
}

const cardLine = /^(\d+)\s+(.+?)(?:\s+\(([A-Za-z0-9]{2,8})\)\s+(\d+[A-Za-z]?))?$/

/** Parses the text generated by MTG Arena's Export command. */
export function parseArenaDecklist(value: string): ParsedArenaDecklist {
  const normalized = value.replace(/\r\n?/g, '\n').trim()
  if (!normalized) throw new Error('Paste an MTG Arena deck export or upload its .txt file.')
  if (normalized.length > 20_000) throw new Error('Deck list is too large.')

  const cards: ArenaDeckCard[] = []
  let section: ArenaDeckSection | undefined
  for (const [index, rawLine] of normalized.split('\n').entries()) {
    const line = rawLine.trim()
    if (!line) continue
    const header = sectionHeaders[line.toLowerCase()]
    if (header) {
      section = header
      continue
    }
    if (!section) throw new Error(`Line ${index + 1}: the export must begin with a Deck header.`)
    const match = line.match(cardLine)
    if (!match) throw new Error(`Line ${index + 1}: expected “quantity card name (SET) number”.`)
    const quantity = Number(match[1])
    if (!Number.isInteger(quantity) || quantity < 1 || quantity > 250) {
      throw new Error(`Line ${index + 1}: card quantity must be between 1 and 250.`)
    }
    cards.push({
      quantity,
      name: match[2].trim(),
      section,
      setCode: match[3],
      collectorNumber: match[4],
    })
  }

  if (!cards.length) throw new Error('The deck export does not contain any card lines.')
  const count = (target: ArenaDeckSection) => cards
    .filter((card) => card.section === target)
    .reduce((total, card) => total + card.quantity, 0)

  return {
    cards,
    mainDeckCount: count('deck'),
    sideboardCount: count('sideboard'),
    companionCount: count('companion'),
  }
}

export function validateStandardArenaDecklist(value: string) {
  const parsed = parseArenaDecklist(value)
  if (parsed.mainDeckCount < 60) throw new Error(`Standard decks need at least 60 main-deck cards; this export has ${parsed.mainDeckCount}.`)
  if (parsed.sideboardCount > 15) throw new Error(`Standard sideboards may contain at most 15 cards; this export has ${parsed.sideboardCount}.`)
  if (parsed.companionCount > 1) throw new Error('An Arena deck export may contain at most one companion.')
  return parsed
}
